//
//  CXURL.h
//  Link
//
//  Created by chx on 14-10-25.
//  Copyright (c) 2014年 rasc. All rights reserved.
//

#import <Foundation/Foundation.h>

// 服务器接口所用基础域名
FOUNDATION_EXPORT NSString *const kBaseURLString;
// 资源文件下载通用域名
FOUNDATION_EXPORT NSString *const kFileBaseUrlString;
// 头像url 前缀
FOUNDATION_EXPORT NSString *const kHeadBaseUrlString;
// 群头像
FOUNDATION_EXPORT NSString *const kGroupLogoBaseUrlString;

#pragma mark - friend model
// 获取好友列表
FOUNDATION_EXPORT NSString *const GET_FRIENDLIST;
// 新的好友列表
FOUNDATION_EXPORT NSString *const GET_NEWFRIENDS;
// 添加好友
FOUNDATION_EXPORT NSString *const GET_ADDFRIEND;
// 拒绝添加好友
FOUNDATION_EXPORT NSString *const GET_ADDFRIEND_REFUSE;
// 同意添加好友
FOUNDATION_EXPORT NSString *const GET_ADDFRIEND_AGREE;
// 搜索好友
FOUNDATION_EXPORT NSString *const GET_SEARCHFRIEND;
// 是否是好友
FOUNDATION_EXPORT NSString *const GET_ISFRIEND; // 手机端未用到
// 删除好友
FOUNDATION_EXPORT NSString *const GET_DELFRIEND; // 手机端未用到
// 修改备注
FOUNDATION_EXPORT NSString *const GET_EDIT_REMARKSNAME;
// 修改备注邮箱
FOUNDATION_EXPORT NSString *const GET_EDIT_REMARKSEMAIL;

#pragma mark - group model
// 获取自己参加的群列表
FOUNDATION_EXPORT NSString *const GET_GROUPLIST;
// 查看群信息
FOUNDATION_EXPORT NSString *const GET_GROUP_VIEW;
// 查看群成员信息
FOUNDATION_EXPORT NSString *const GET_GROUP_MEMBERS;
// 创建群
FOUNDATION_EXPORT NSString *const POST_CREATE_GROUP;
// 修改群头像
FOUNDATION_EXPORT NSString *const POST_GROUP_MODIFYLOGO;
// 修改群名称
FOUNDATION_EXPORT NSString *const POST_GROUP_MODIFYNAME;
// 修改群介绍
FOUNDATION_EXPORT NSString *const POST_GROUP_MODIFYDESC;
// 添加群成员
FOUNDATION_EXPORT NSString *const GET_GROUP_ADDMEMBER;
// 搜索群
FOUNDATION_EXPORT NSString *const GET_GROUP_SEARCH;
// 申请群
FOUNDATION_EXPORT NSString *const GET_GROUP_APPLY;
// 退群
FOUNDATION_EXPORT NSString *const GET_GROUP_QUIT;
// 删除群
FOUNDATION_EXPORT NSString *const GET_GROUP_DEL;

#pragma mark - user model
// 查看用户信息
FOUNDATION_EXPORT NSString *const GET_USERINFO;
// 修改头像
FOUNDATION_EXPORT NSString *const POST_ME_MODIFY_USERHEAD;
// 修改用户信息
FOUNDATION_EXPORT NSString *const POST_ME_MODIFY_USERINFO;
// 修改背景图
FOUNDATION_EXPORT NSString *const POST_ME_MODIFY_BGIMAGE;
// 我的推荐人
FOUNDATION_EXPORT NSString *const GET_USER_RECOMMENT;
// 推荐通讯录好友
FOUNDATION_EXPORT NSString *const GET_USER_RECOMMENT_CONTRACT;
// 推荐所有通讯录好友
FOUNDATION_EXPORT NSString *const GET_USER_RECOMMENT_ALLCONTRACT;
// 我的推荐
FOUNDATION_EXPORT NSString *const GET_USER_LISTMYRECOMMENT;
// 我的积分
FOUNDATION_EXPORT NSString *const GET_USER_MYINTEGRAL;
// 我的积分详情
FOUNDATION_EXPORT NSString *const GET_USER_LISTMYINTEGRAL;
//我的资讯收藏
FOUNDATION_EXPORT NSString *const GET_USER_FAVORITEINFOLIST;

#pragma mark - system model
// 登录
FOUNDATION_EXPORT NSString *const GET_LOGIN;
// 登出
FOUNDATION_EXPORT NSString *const GET_LOGOUT;
// 注册
FOUNDATION_EXPORT NSString *const GET_REGBYEMAIL;
// 邮件找回密码
FOUNDATION_EXPORT NSString *const GET_FINDPWD_MAIL;
// 修改密码
FOUNDATION_EXPORT NSString *const GET_EDITPWD;
// 获取验证码
FOUNDATION_EXPORT NSString *const GET_AUTHCODE;
// 校验 验证码
FOUNDATION_EXPORT NSString *const GET_VERIFY_AUTHCODE;
// 手机注册
FOUNDATION_EXPORT NSString *const GET_REGBYPHONE;
// 找回密码，得验证码
FOUNDATION_EXPORT NSString *const GET_FINDPWDSMS;
// 找回密码
FOUNDATION_EXPORT NSString *const GET_EDITPWD_BYPHONE;
// 重置密码（唯一一次））
FOUNDATION_EXPORT NSString *const GET_RESET_USERPWD;

// 版本更新
FOUNDATION_EXPORT NSString *const GET_SYSTEM_UPDATE ;
// 启动页广告
FOUNDATION_EXPORT NSString *const GET_BANNER_LISTSTARTUPTPIC;

// 意见反馈
FOUNDATION_EXPORT NSString *const GET_SYSTEM_FEEDBACK;

#pragma mark - activity
FOUNDATION_EXPORT NSString *const GET_POPACTIVITY;
// 分享活动成功回调
FOUNDATION_EXPORT NSString *const GET_SHAREACTIVITY;
// 邀请有礼成功回调
FOUNDATION_EXPORT NSString *const GET_ACTIVITY_INVITESHARE;

#pragma mark - banner
// 获取banner
FOUNDATION_EXPORT NSString *const GET_BANNERS;

#pragma mark -information
// 获取资讯
FOUNDATION_EXPORT NSString *const GET_INFORMATIONS;
// 获取推荐资讯
FOUNDATION_EXPORT NSString *const GET_INFORMATION_RECOMMENDS;
// 资讯详情
FOUNDATION_EXPORT NSString *const GET_INFORMATION_DETAIL;
// 资讯阅读者
FOUNDATION_EXPORT NSString *const GET_INFORMATION_READER;
// 资讯点赞者
FOUNDATION_EXPORT NSString *const GET_INFORMATION_FAVORS;
// 资讯点赞
FOUNDATION_EXPORT NSString *const GET_INFORMATION_FAVOR;
// 资讯收藏
FOUNDATION_EXPORT NSString *const GET_INFORMATION_FAVORITEINFO;
//资讯筛选条件的接口(最热最新等)
FOUNDATION_EXPORT NSString *const GET_INFORMATION_LISTCONDITIONCATEGORY;
//首页上证指数，深证指数等
FOUNDATION_EXPORT NSString *const GET_INFORMATION_FINDSHARELIST;
// 资讯分类列表
//FOUNDATION_EXPORT NSString *const GET_INFORMATION_LISTBYCATEGORY;
FOUNDATION_EXPORT NSString *const GET_INFORMATION_SEARCH ;
FOUNDATION_EXPORT NSString *const GET_INFORMATION_LISTCATEGORY ;

#pragma mark - product
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LIST;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_DETAIL;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_SEARCH;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_SUBSCRIBE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_RELEASE;
//受让信托
FOUNDATION_EXPORT NSString *const GET_BUYBACK_RELEASE;
//我的受让信托
FOUNDATION_EXPORT NSString *const GET_BUYBACK_LISTMYBUYBACK;
//删除我的受让信托
FOUNDATION_EXPORT NSString *const  GET_BUYBACK_DELRELEASE;

FOUNDATION_EXPORT NSString *const GET_PRODUCT_DELSUBSCRIBE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_DELRELEASE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTMYSUBSCRIBE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTMYRELEASE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTCHOICE;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_ATTENTION;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTATTENTION;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTCATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTINVESTCATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTTRUSTCATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTFUNDCATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTSHIBOSAICATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTCONDCATEGORY;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_SEARCHCOND;
FOUNDATION_EXPORT NSString *const GET_PRODUCT_SUBSCRIBE_OP; // 预约-替换或叠加
//产品进度轨迹
FOUNDATION_EXPORT NSString *const GET_PRODUCT_LISTSCHEDULE;
//产品详情网页版
FOUNDATION_EXPORT NSString *const GET_PRODUCT_WEBLIST;
//产品分享邮件接口
FOUNDATION_EXPORT NSString *const GET_USER_SENDPRODINFO;
#pragma mark -二手信托
//二手信托首页
FOUNDATION_EXPORT NSString *const GET_PRODUCT_SCONDPROINFO;
//二手信托广告图
FOUNDATION_EXPORT NSString *const GET_BANNER_SECONDHOMEPAGE;
#pragma mark - 信托宝

// 信托宝列表
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_PRODUCTLIST;
// 信托宝详情
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_DETAIL;
// 查询用户在信托宝的信息
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_FINDUSERINFO;
// 查询用户在信托宝的账户信息
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_FINDUSERFUND;
// 查询用户在信托宝的交易记录信息
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_FINDINVESTLIST;
// 查询信托宝的资金流水产品
FOUNDATION_EXPORT NSString *const GET_XINTUOBAO_FINDBILLLIST;

//理财学堂模块列表
FOUNDATION_EXPORT NSString *const GET_BANNER_LISTCOURSE;
FOUNDATION_EXPORT NSString *const GET_COURSE_LISTMODULES;
FOUNDATION_EXPORT NSString *const GET_COURSE_LISTRECOMMENT;
FOUNDATION_EXPORT NSString *const GET_COURSE_LIST;
FOUNDATION_EXPORT NSString *const GET_COURSE_VIEW;
FOUNDATION_EXPORT NSString *const GET_COURSE_SEARCH;
FOUNDATION_EXPORT NSString *const GET_COURSE_LISTCATEGRORY;
FOUNDATION_EXPORT NSString *const GET_COURSE_FAVOR;



//理财轨迹上传
FOUNDATION_EXPORT NSString *const GET_TRACK_RELEASE;
//我的理财轨迹
FOUNDATION_EXPORT NSString *const GET_TRACK_LISTMYTRACK;
//删除理财轨迹
FOUNDATION_EXPORT NSString *const GET_TRACK_DELRELEASE;

//信托转让列表
FOUNDATION_EXPORT NSString *const GET_BENEFIT_LISTBENFIT;
// 信托转让认购详情(不调)
FOUNDATION_EXPORT NSString *const GET_BENEFIT_VIEW;
//信托转让认购记录
FOUNDATION_EXPORT NSString *const GET_BENEFIT_LISTBENFITRECORD;
// 信托转让我要预约
FOUNDATION_EXPORT NSString *const GET_BENEFIT_SUBSCRIBE;
//信托转让取消预约
FOUNDATION_EXPORT NSString *const GET_BENEFIT_CENCELSUBSCRIBE;

//信托受让列表（信托受让中心）
FOUNDATION_EXPORT NSString *const GET_BUYBACK_LISTBUYBACK;
// 信托受让认购详情(不调)
FOUNDATION_EXPORT NSString *const GET_BUYBACK_VIEW;
//信托受让认购记录
FOUNDATION_EXPORT NSString *const GET_BUYBACK_LISTBUYBACKRECORD;
// 信托转让我要预约
FOUNDATION_EXPORT NSString *const GET_BUYBACK_SUBSCRIBE;
//信托转让取消预约
FOUNDATION_EXPORT NSString *const GET_BUYBACK_CENCELSUBSCRIBE;


//受益权转让上传
FOUNDATION_EXPORT NSString *const GET_BENEFIT_RELEASE;
//我的受益权转让
FOUNDATION_EXPORT NSString *const GET_BENEFIT_LISTMYRELEASE;
//删除受益权转让
FOUNDATION_EXPORT NSString *const GET_BENEFIT_DELRELEASE;

//邀请返利
FOUNDATION_EXPORT NSString *const GET_SYSTEM_RETURNPROFIT;

#pragma mark - 理财师
//保存理财师
FOUNDATION_EXPORT NSString *const GET_USER_SAVAFINANCIAL;
//获取理财师列表
FOUNDATION_EXPORT NSString *const GET_USER_FINANCIALLIST;
//获取我的专属理财师
FOUNDATION_EXPORT NSString *const GET_USER_MYFINANCIAL;
//理财师上传照片认证-
FOUNDATION_EXPORT NSString *const GET_FINANCIAL_UPPHOTO;
//编辑理财师资料
FOUNDATION_EXPORT NSString *const GET_FINANCIAL_EDITQUALITYL;
//金牌理财师列表
FOUNDATION_EXPORT NSString *const GET_FINANCIAL_LIST ;
//查询金牌理财师资质、积分、发布的产品
NSString *const GET_FINANCIAL_FINANCIALPRO ;
//查询金牌理财师详情
FOUNDATION_EXPORT NSString *const GET_FINANCIAL_FINANCIAINFO;
//名家专栏
FOUNDATION_EXPORT NSString *const GET_SPECIALIST_LISTRECOMMENT;
//名家专栏列表
FOUNDATION_EXPORT NSString *const GET_COURSE_LISTCOURSE;

#pragma mark - 通知消息
//获取云端通知数据
FOUNDATION_EXPORT NSString *const GET_USER_LISTMESSAGE;


#pragma mark - web url

FOUNDATION_EXPORT NSString *const WEB_ABOUT;
FOUNDATION_EXPORT NSString *const WEB_XTB_FAQ; // 信托宝，常见问题

#pragma mark - cooperate model


@interface CXURLConstants : NSObject

+ (NSString *)getFullImageUrl:(NSString *)imageName;
+ (NSString *)getFullHeaderUrl:(NSString *)headerImageName;
+ (NSString *)getFullSltHeaderUrl:(NSString *)headerImageName;
+ (NSString *)getFullStatusUrl:(NSString *)imageName;
+ (NSString *)getFullAudioUrl:(NSString *)audioFileName;
+ (NSString *)getGroupLogoImageUrl:(NSString *)imageName;
+ (NSString *)getFullSltGroupLogoImageUrl:(NSString *)imageName;
+ (NSString *)getBannerImageUrl:(NSString *)imageName;
+ (NSString *)getFullInformationUrl:(NSString *)imageName;
+ (NSString *)getFullSltInformationUrl:(NSString *)imageName;

+ (NSString *)getFullInformationCategoryUrl:(NSString *)imageName;
+ (NSString *)getFullProductCategoryUrl:(NSString *)imageName;

+ (NSString *)getWebUrl:(NSString *)urlString;

@end
